---
title: "modified_for_gaussian"
author: "Mohan Zhao"
date: "20/08/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r cars}
library(myTridge)
library(glmnet)
library(rsvd)
pacman::p_load_gh("r-lib/bench")
library(profvis)
```

# New version of TridgeEst using rsvd, svd and woodbury in Rcpp
```{r}
TridgeEst_new1<-function(X,y,family=c("gaussian","binomial","poisson"),type=c("rsvd","svd","woodbury"),nlambda=1000,lambda.min.limit=0.05,c=0.1,nfolds=10,alpha=0,stn=10){
  family=match.arg(family)
  type=match.arg(type)
  
  if(family=="gaussian") {
    TREX.c.vector <- 2 
  } else {
    TREX.c.vector <- 1
  }
  num.obs <- nrow(X)
  num.par <- ncol(X)
  
  ##### signal-to-noise ratio for gaussian family case 
  if(family == "gaussian") {
    stn <- stn # signal-to-noise ratio
  }else{
    stn <- NA
  }
  ###compute T-ridge estimators
  par0 <-rep(0,num.par)
  par1 <- optim_ObLs(par0,X,y,family)
  
  GlmTrex.estimators <- matrix(nrow=num.par, ncol=length(TREX.c.vector))
  for(trex.e in 1:length(TREX.c.vector)) {
    TREX.c <- TREX.c.vector[trex.e]
    ###find the stationary point
    GlmTrex.estimation <- optim_ObFn(par1,X,y,family,TREX.c)
    GlmTrex.estimators[, trex.e] <- GlmTrex.estimation
    
  }
  
  edr.lambda <- Lqnorm(2,GradientLs(GlmTrex.estimators,X,y,family)) / (2 * Lqnorm(2, GlmTrex.estimators))
  r.max <- edr.lambda + c
  r.min <- max(lambda.min.limit, (edr.lambda - c))
  if(r.min == Inf || r.max == Inf ) {
    tuning.parameters <- seq(1e+10, 1e+11, length.out=nlambda)
  } else {
    tuning.parameters <- seq(r.min, r.max, length.out=nlambda)
  }
  if(family!="gaussian"){
    init <- cv.glmnet(X, y, nfolds=nfolds, alpha=alpha, family=family)
    init.estimation <- glmnet(X, y, alpha=alpha, family=family, lambda=init$lambda.min)
    init.vector <- as.vector(coef(init.estimation))[-1]
  }
  if(type=="rsvd"){
    svd<-rsvd(X)
    v<-svd$v
    d<-svd$d
    u<-svd$u
    d<-diag(d)
  }else if(type=="svd"){
    svd<-base::svd(X)
    v<-svd$v
    d<-svd$d
    u<-svd$u
    d<-diag(d)
  }else{
  }
  Ridge.estimators <- matrix(nrow=num.par, ncol=nlambda)
  cost <- rep(0, nlambda)
  
  estimator <-Ridgefunction(TREX.c,Ridge.estimators,cost,init.vector,tuning.parameters,nlambda,num.obs,num.par,u,d,v,X,y,family,type)
  return(estimator)
}
```