# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mvrnormArma <- function(n, mu, p, rho) {
    .Call(`_myTridge_mvrnormArma`, n, mu, p, rho)
}

rpois_rcpp <- function(lambda) {
    .Call(`_myTridge_rpois_rcpp`, lambda)
}

cpprbinom <- function(n, size, prob) {
    .Call(`_myTridge_cpprbinom`, n, size, prob)
}

genDataList <- function(n, mu, p, rho, beta, SNR, Test_case) {
    .Call(`_myTridge_genDataList`, n, mu, p, rho, beta, SNR, Test_case)
}

bFunction <- function(X, theta, Test_case) {
    .Call(`_myTridge_bFunction`, X, theta, Test_case)
}

MeanFunction <- function(X, theta, Test_case) {
    .Call(`_myTridge_MeanFunction`, X, theta, Test_case)
}

MeanPrime <- function(X, theta, Test_case) {
    .Call(`_myTridge_MeanPrime`, X, theta, Test_case)
}

ObjectiveFunction <- function(theta, Test_case, y, X, trex_c) {
    .Call(`_myTridge_ObjectiveFunction`, theta, Test_case, y, X, trex_c)
}

Gradient <- function(theta, Test_case, y, X, trex_c) {
    .Call(`_myTridge_Gradient`, theta, Test_case, y, X, trex_c)
}

GradientLs <- function(theta, X, y, Test_case) {
    .Call(`_myTridge_GradientLs`, theta, X, y, Test_case)
}

optim_ObLs <- function(theta, X, y, Test_case) {
    .Call(`_myTridge_optim_ObLs`, theta, X, y, Test_case)
}

optim_Ridge <- function(theta, X, y, Test_case, r) {
    .Call(`_myTridge_optim_Ridge`, theta, X, y, Test_case, r)
}

optim_ObFn <- function(theta, X, y, Test_case, trex_c) {
    .Call(`_myTridge_optim_ObFn`, theta, X, y, Test_case, trex_c)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_myTridge_RcppExport_registerCCallable', PACKAGE = 'myTridge')
})
